stages:
  - plan
  - security

include:
  - local: "/templates/planning/generate-security-pipeline.yml"
  - local: "/templates/planning/run-dynamic-security-pipeline.yml"
  - local: "/templates/planning/run-static-security-fallback.yml"